use crate::*;

impl<S, E> AppService<S>
where
    S: AccountStore<Error = E> + AdmissionStore<Error = E> + MessageStore<Error = E>,
{
    /// Ensures the player's wallet exists when admission has been accepted.
    pub async fn ensure_player_wallet_if_admitted(
        &self,
        username: &str,
        player_id: &str,
    ) -> Result<bool, E> {
        let admission = self.player_admission(player_id).await?;
        if !admission.is_agreed() {
            return Ok(false);
        }
        self.store.ensure_player_wallet(username, player_id).await?;
        Ok(true)
    }

    /// Ensures the player's wallet exists and issues the initial grant if needed.
    pub async fn ensure_player_wallet(&self, username: &str, player_id: &str) -> Result<(), E> {
        self.store.ensure_player_wallet(username, player_id).await
    }

    /// Loads the player's current MARK balance.
    pub async fn player_balance(&self, player_id: &str) -> Result<S::Balance, E>
    where
        S: MessageStore<Error = E>,
    {
        self.store.player_balance(player_id).await
    }
}

impl<S, E> AppService<S>
where
    S: AccountStore<Error = E>,
{
    /// Counts admitted players in the world.
    pub async fn admitted_player_count(&self) -> Result<usize, E> {
        self.store.admitted_player_count().await
    }

    /// Builds account settings text.
    pub async fn show_account_settings(
        &self,
        username: &str,
        player_id: &str,
        mail_address: &str,
    ) -> Result<SettingsResult, E> {
        let settings = self.store.account_settings(username, player_id).await?;
        let key = settings.key_fingerprint().unwrap_or("not set");
        let mut next_steps = Vec::new();
        if !settings.has_mail_token() {
            next_steps.push("Generate your SMTP/IMAP token with /settings mail-token.");
        }
        if !role_card_name_is_valid(settings.display_name()) {
            next_steps.push("Choose a valid role-card name with /settings name <name>.");
        }
        if settings.mbti().is_none() {
            next_steps.push("Complete your role card with /settings mbti <type>.");
        }
        let next_steps = if next_steps.is_empty() {
            "Next steps: account settings are complete.\r\n".to_owned()
        } else {
            format!("Next steps:\r\n- {}\r\n", next_steps.join("\r\n- "))
        };
        let agent_protocol = format!(
            "Agent realtime mail:\r\n- Login: IMAP/SMTP username `{}`; token is generated by `/settings mail-token`.\r\n- Setup: use ed25519 SSH login for account access.\r\n- Listen: keep an IMAP IDLE connection open; when EXISTS arrives, FETCH the new message, handle it, then STORE +FLAGS (\\Seen). This is the supported no-prompt path for autonomous agents.\r\n- Room services receive subjects like `Room command #<id> for <view_id>` and should reply with `Re: #<id>` to keep the request thread intact.\r\n",
            username
        );
        let role_card = render_role_card(&settings);
        Ok(SettingsResult {
            text: format!(
                "Settings\r\nUser: {}\r\nPlayer: {}\r\nOnline days: {}\r\nSSH key: {}\r\nMail address: {}\r\nMail token: {}\r\n{}{}{}Use /settings mail-token to generate or rotate your SMTP/IMAP token.\r\n",
                username,
                settings.player_id(),
                settings.online_days(),
                key,
                mail_address,
                enabled_label(settings.has_mail_token()),
                role_card,
                next_steps,
                agent_protocol,
            ),
        })
    }

    /// Updates one role-card field and returns refreshed settings text.
    pub async fn update_role_card(
        &self,
        username: &str,
        player_id: &str,
        update: RoleCardUpdate,
        mail_address: &str,
    ) -> Result<SettingsResult, E> {
        self.store.update_role_card(player_id, update).await?;
        let settings = self
            .show_account_settings(username, player_id, mail_address)
            .await?;
        Ok(SettingsResult {
            text: format!("Updated role card.\r\n{}", settings.text),
        })
    }

    /// Rotates a user's mail token and returns setup text.
    pub async fn rotate_user_mail_token(
        &self,
        username: &str,
        player_id: &str,
        mail_address: &str,
        token: &str,
    ) -> Result<MailTokenResult, E> {
        self.store
            .set_mail_auth_token(username, player_id, token)
            .await?;
        Ok(MailTokenResult {
            text: format!(
                "Generated a new SMTP/IMAP mail auth token.\r\nUsername: {}\r\nAddress: {}\r\nToken: {}\r\nThis token is shown once; run /settings mail-token again to rotate it.\r\nAgent setup: configure SMTP and IMAP with this username/token. For realtime autonomous handling, keep an IMAP IDLE listener open and process EXISTS notifications without waiting for a world prompt. Room service replies should use subject `Re: #<id>` for request subjects like `Room command #<id> for <view_id>`.\r\n",
                username, mail_address, token
            ),
        })
    }
}

impl<S, E> AppService<S>
where
    S: AdmissionStore<Error = E>,
{
    /// Attempts to accept admission under the active agreement.
    pub async fn accept_admission(&self, player_id: &str) -> Result<AdmissionAcceptResult, E> {
        let admission = self.store.player_admission(player_id).await?;
        if admission.is_agreed() {
            return Ok(AdmissionAcceptResult::AlreadyAgreed {
                text: "Admission already agreed. Welcome back.\r\n".to_owned(),
            });
        }
        if !admission.has_read_version(&self.config.agreement_version) {
            return Ok(AdmissionAcceptResult::NeedsRead {
                text: self.admission_guidance(&admission).replace('\n', "\r\n"),
            });
        }
        if !admission.role_card_is_complete() {
            return Ok(AdmissionAcceptResult::NeedsRoleCard {
                text: self.admission_guidance(&admission).replace('\n', "\r\n"),
            });
        }
        self.store
            .admit_player(player_id, &self.config.agreement_version)
            .await?;
        Ok(AdmissionAcceptResult::Accepted)
    }
}

/// Protocol-neutral view of a mail auth token identity.
pub trait MailAuthTokenView {
    /// Username used for SMTP/IMAP login.
    fn username(&self) -> &str;

    /// Stable player id used by the runtime.
    fn player_id(&self) -> &str;
}

/// Protocol-neutral account settings view.
pub trait AccountSettingsView {
    /// Stable player id.
    fn player_id(&self) -> &str;

    /// Display name.
    fn display_name(&self) -> &str;

    /// Role-card gender.
    fn gender(&self) -> &str;

    /// Role-card MBTI type, if set.
    fn mbti(&self) -> Option<&str>;

    /// Optional one-line self introduction.
    fn self_intro(&self) -> Option<&str>;

    /// Returns true when required role-card fields are complete.
    fn role_card_is_complete(&self) -> bool {
        role_card_name_is_valid(self.display_name()) && self.mbti().is_some()
    }

    /// Full days online.
    fn online_days(&self) -> i32;

    /// True when mail auth token exists.
    fn has_mail_token(&self) -> bool;

    /// Current SSH key fingerprint, if any.
    fn key_fingerprint(&self) -> Option<&str>;
}

/// Storage boundary for account settings.
pub trait AccountStore {
    /// Store error type.
    type Error;
    /// Stored account settings type.
    type AccountSettings: AccountSettingsView;
    /// Stored mail auth token type.
    type MailAuthToken: MailAuthTokenView;

    /// Loads account settings.
    async fn account_settings(
        &self,
        username: &str,
        player_id: &str,
    ) -> Result<Self::AccountSettings, Self::Error>;

    /// Counts admitted players in the world.
    async fn admitted_player_count(&self) -> Result<usize, Self::Error>;

    /// Sets or rotates the player's mail token.
    async fn set_mail_auth_token(
        &self,
        username: &str,
        player_id: &str,
        token: &str,
    ) -> Result<(), Self::Error>;

    /// Updates one role-card field.
    async fn update_role_card(
        &self,
        player_id: &str,
        update: RoleCardUpdate,
    ) -> Result<(), Self::Error>;

    /// Verifies a username/token pair for SMTP or IMAP login.
    async fn verify_mail_auth_token(
        &self,
        username: &str,
        token: &str,
    ) -> Result<Option<Self::MailAuthToken>, Self::Error>;

    /// Ensures the player has a wallet and receives the one-time grant if needed.
    async fn ensure_player_wallet(
        &self,
        username: &str,
        player_id: &str,
    ) -> Result<(), Self::Error>;
}

/// Result from showing account settings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SettingsResult {
    /// Text to display to the user.
    pub text: String,
}

/// Result from rotating a user mail token.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MailTokenResult {
    /// Text to display to the user.
    pub text: String,
}

/// Validated role-card field update.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RoleCardUpdate {
    /// Update role-card name.
    Name(String),
    /// Update role-card gender.
    Gender(Gender),
    /// Update role-card MBTI type.
    Mbti(MbtiType),
    /// Update or clear one-line self introduction.
    Intro(Option<String>),
}

impl RoleCardUpdate {
    /// Converts a settings action to a role-card update when applicable.
    #[must_use]
    pub fn from_settings_action(action: &SettingsAction) -> Option<Self> {
        match action {
            SettingsAction::Name { name } => Some(Self::Name(name.clone())),
            SettingsAction::Gender { gender } => Some(Self::Gender(*gender)),
            SettingsAction::Mbti { mbti } => Some(Self::Mbti(*mbti)),
            SettingsAction::Intro { intro } => Some(Self::Intro(intro.clone())),
            SettingsAction::Show | SettingsAction::MailToken => None,
        }
    }
}

fn render_role_card(settings: &impl AccountSettingsView) -> String {
    format!(
        "Role card:\r\n- Name: {}\r\n- Gender: {}\r\n- MBTI: {}\r\n- Intro: {}\r\nRole-card commands: /settings name <name>, /settings gender <male|female|none>, /settings mbti <type>, /settings intro <one line>, /settings intro clear.\r\n",
        settings.display_name(),
        settings.gender(),
        settings.mbti().unwrap_or("not set"),
        settings.self_intro().unwrap_or("not set"),
    )
}
