use crate::*;

/// Protocol-neutral request variants currently handled inside `hinemos-app`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AppRequest<'a> {
    /// Build the login memory summary.
    MemoryContext,
    /// Handle a `/memory` subcommand.
    MemoryCommand {
        /// Text after `/memory`.
        rest: &'a str,
    },
    /// Render recent messages for the current room.
    RoomHistory {
        /// Current runtime view id.
        current_view: &'a str,
        /// Current room title.
        title: &'a str,
    },
    /// Render the current player's inventory.
    Inventory {
        /// Current runtime inventory items.
        items: &'a [String],
    },
    /// Render users currently online in this view.
    Who {
        /// Current runtime view id.
        current_view: &'a str,
        /// Usernames currently visible in this view.
        users: &'a [String],
        /// Population counts for the world and online sessions.
        population: WhoPopulation,
    },
    /// Render recent world news.
    News,
    /// Render the current player's MARK balance.
    Balance,
    /// List inbox items.
    InboxList {
        /// Display title.
        title: &'a str,
        /// Inbox filter such as `open`, `unread`, or `all`.
        filter: &'a str,
        /// Optional mail domain for display addresses.
        mail_domain: Option<&'a str>,
    },
    /// Read one inbox item.
    InboxRead {
        /// Inbox item id.
        item_id: i64,
        /// Optional mail domain for display addresses.
        mail_domain: Option<&'a str>,
    },
    /// Claim one inbox item.
    InboxClaim {
        /// Inbox item id.
        item_id: i64,
    },
    /// Acknowledge one inbox item.
    InboxAck {
        /// Inbox item id.
        item_id: i64,
    },
    /// Archive one inbox item.
    InboxArchive {
        /// Inbox item id.
        item_id: i64,
    },
    /// Show the current player's shop operator inbox.
    ShopInbox,
    /// Show pending payment requests for the current player.
    PendingPayRequests,
    /// Transfer MARK directly to another account.
    PayDirect {
        /// Target username or player id.
        target: &'a str,
        /// Positive MARK amount.
        amount: i64,
        /// Payment memo.
        memo: &'a str,
    },
    /// Accept a pending payment request.
    PayAccept {
        /// Payment request id.
        request_id: i64,
    },
    /// List commercial parcels.
    LandList,
    /// Show commercial parcel details.
    LandInfo {
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Show build command help.
    BuildHelp,
    /// Claim a commercial parcel and provision its room mailbox token.
    LandClaim {
        /// Parcel id.
        parcel_id: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Transfer a commercial parcel and rotate its room mailbox token.
    LandTransfer {
        /// Parcel id.
        parcel_id: &'a str,
        /// Target username.
        target: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Rotate a parcel room mailbox token.
    LandRotateToken {
        /// Parcel id.
        parcel_id: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Apply a structured build sheet to the current parcel room.
    BuildApply {
        /// Current room view id.
        current_view: &'a str,
        /// Structured build sheet.
        sheet: &'a BuildSheet,
    },
    /// Set one build field on the current parcel room.
    BuildSet {
        /// Current room view id.
        current_view: &'a str,
        /// Build field name.
        field: &'a str,
        /// Build field value.
        value: &'a str,
    },
    /// Publish the current parcel room build.
    BuildPublish {
        /// Current room view id.
        current_view: &'a str,
    },
    /// Create a payment request for a shop command.
    ShopRequestPayment {
        /// Operator command id.
        command_id: i64,
        /// Positive MARK amount.
        amount: i64,
        /// Delivery content unlocked after payment.
        delivery: &'a str,
    },
    /// Persist a same-view say message and emit live delivery events.
    Say {
        /// Current room view id.
        current_view: &'a str,
        /// Spoken text.
        text: &'a str,
    },
    /// Persist a direct mail message.
    Mail {
        /// Target mail address or user.
        target: &'a str,
        /// Mail body.
        text: &'a str,
    },
    /// Persist a broadcast message.
    Broadcast {
        /// Broadcast body.
        text: &'a str,
    },
    /// Forward input to an externally hosted service room.
    ServiceRoomInput {
        /// Current service room view id.
        room_view: &'a str,
        /// Raw input to forward.
        raw_input: &'a str,
    },
    /// Render contextual service-room help.
    ServiceRoomHelp {
        /// Current service room view id.
        room_view: &'a str,
    },
    /// Render a structured service-room observation.
    ServiceRoomObservation {
        /// Current service room view id.
        room_view: &'a str,
    },
    /// Render a service-room blocked-exit message.
    ServiceRoomBlockedExit,
    /// Render a service-room unavailable-command message.
    ServiceRoomUnavailable,
    /// Close the current service-room session.
    ServiceRoomQuit {
        /// Quit feedback text supplied by the protocol shell.
        feedback: &'a str,
    },
    /// Mark the active admission agreement as read.
    AdmissionRead,
    /// Accept the active admission agreement.
    AdmissionAccept,
    /// Show account settings.
    Settings {
        /// Display mail address.
        mail_address: &'a str,
    },
    /// Rotate the current user's SMTP/IMAP token.
    SettingsRotateMailToken {
        /// Display mail address.
        mail_address: &'a str,
        /// One-time mail token generated by the caller.
        token: &'a str,
    },
}
