use crate::*;

/// Protocol-neutral request variants currently handled inside `hinemos-app`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AppRequest<'a> {
    /// Build the login memory summary.
    MemoryContext,
    /// Handle a `/memory` subcommand.
    MemoryCommand {
        /// Text after `/memory`.
        rest: &'a str,
    },
    /// Render recent messages for the current room.
    RoomHistory {
        /// Current runtime view id.
        current_view: &'a str,
        /// Current room title.
        title: &'a str,
    },
    /// Render the current player's inventory.
    Inventory {
        /// Current runtime inventory items.
        items: &'a [String],
    },
    /// Render users currently online in this view.
    Who {
        /// Current runtime view id.
        current_view: &'a str,
        /// Usernames currently visible in this view.
        users: &'a [String],
        /// Population counts for the world and online sessions.
        population: WhoPopulation,
    },
    /// Render recent world news.
    News,
    /// Render the current player's MARK balance.
    Balance,
    /// List inbox items.
    InboxList {
        /// Display title.
        title: &'a str,
        /// Inbox filter such as `open`, `unread`, or `all`.
        filter: &'a str,
        /// Optional mail domain for display addresses.
        mail_domain: Option<&'a str>,
    },
    /// Read one inbox item.
    InboxRead {
        /// Inbox item id.
        item_id: i64,
        /// Optional mail domain for display addresses.
        mail_domain: Option<&'a str>,
    },
    /// Claim one inbox item.
    InboxClaim {
        /// Inbox item id.
        item_id: i64,
    },
    /// Acknowledge one inbox item.
    InboxAck {
        /// Inbox item id.
        item_id: i64,
    },
    /// Archive one inbox item.
    InboxArchive {
        /// Inbox item id.
        item_id: i64,
    },
    /// Show the current parcel's operator inbox while inside that parcel.
    ParcelInbox {
        /// Current runtime view id.
        current_view: &'a str,
    },
    /// Show pending payment requests for the current player.
    PendingPayRequests,
    /// Transfer MARK directly to another account.
    PayDirect {
        /// Target username or player id.
        target: &'a str,
        /// Positive MARK amount.
        amount: i64,
        /// Payment memo.
        memo: &'a str,
    },
    /// Accept a pending payment request.
    PayAccept {
        /// Payment request id.
        request_id: i64,
    },
    /// List parcels.
    ParcelList,
    /// Show parcel details.
    ParcelInfo {
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Show build command help.
    ParcelBuildHelp,
    /// Claim a parcel and provision its room mailbox token.
    ParcelClaim {
        /// Parcel id.
        parcel_id: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Transfer a parcel and rotate its room mailbox token.
    ParcelTransfer {
        /// Parcel id.
        parcel_id: &'a str,
        /// Target username.
        target: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Rotate a parcel room mailbox token.
    ParcelRotateToken {
        /// Parcel id.
        parcel_id: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Apply a structured build sheet to the current parcel room.
    ParcelBuildApply {
        /// Current room view id.
        current_view: &'a str,
        /// Structured build sheet.
        sheet: &'a BuildSheet,
    },
    /// Set one build field on the current parcel room.
    ParcelBuildSet {
        /// Current room view id.
        current_view: &'a str,
        /// Build field name.
        field: &'a str,
        /// Build field value.
        value: &'a str,
    },
    /// Publish the current parcel room build.
    ParcelBuildPublish {
        /// Current room view id.
        current_view: &'a str,
    },
    /// Create a payment request for a parcel command.
    ParcelRequestPayment {
        /// Current runtime view id.
        current_view: &'a str,
        /// Operator command id.
        command_id: i64,
        /// Positive MARK amount.
        amount: i64,
        /// Delivery content unlocked after payment.
        delivery: &'a str,
    },
    /// Create a mailing list for an owned parcel.
    ParcelMailingListCreate {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable list slug.
        slug: &'a str,
        /// Player-facing list title.
        title: &'a str,
    },
    /// List mailing lists for an owned parcel.
    ParcelMailingListList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Show mailing-list subscribers for an owned parcel.
    ParcelMailingListSubscribers {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable list slug.
        slug: &'a str,
    },
    /// Send an owner-authored mailing-list post.
    ParcelMailingListSend {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable list slug.
        slug: &'a str,
        /// Inbox subject.
        subject: &'a str,
        /// Inbox body.
        body: &'a str,
    },
    /// Post a group-chat message to a parcel mailing list.
    ParcelMailingListChat {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id or visible parcel title.
        target: &'a str,
        /// Stable list slug.
        slug: &'a str,
        /// Message body.
        body: &'a str,
    },
    /// Close a mailing list to new subscriptions.
    ParcelMailingListClose {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable list slug.
        slug: &'a str,
    },
    /// Subscribe the current player to a parcel mailing list.
    ParcelMailingListSubscribe {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id or visible parcel title.
        target: &'a str,
        /// Stable list slug.
        slug: &'a str,
    },
    /// Unsubscribe the current player from a parcel mailing list.
    ParcelMailingListUnsubscribe {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id or visible parcel title.
        target: &'a str,
        /// Stable list slug.
        slug: &'a str,
    },
    /// List the current player's parcel mailing-list subscriptions.
    ParcelMailingListSubscriptions,
    /// Create a parcel-local work desk.
    ParcelDeskCreate {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Player-facing work-desk title.
        title: &'a str,
    },
    /// List parcel-local work desks.
    ParcelDeskList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Add a worker to a parcel-local work desk.
    ParcelStaffAdd {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Worker username.
        username: &'a str,
    },
    /// List workers assigned to a parcel-local work desk.
    ParcelStaffList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
    },
    /// Remove a worker from a parcel-local work desk.
    ParcelStaffRemove {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Worker username.
        username: &'a str,
    },
    /// Start an in-parcel work shift.
    ParcelShiftStart {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
    },
    /// End an in-parcel work shift.
    ParcelShiftEnd {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
    },
    /// List parcel work while inside the parcel.
    ParcelWorkList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Optional stable work-desk slug.
        slug: Option<&'a str>,
    },
    /// Claim parcel work while inside the parcel.
    ParcelWorkClaim {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Work item id.
        work_id: i64,
    },
    /// Complete claimed parcel work while inside the parcel.
    ParcelWorkDone {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Work item id.
        work_id: i64,
        /// Worker result note.
        result: &'a str,
    },
    /// Add a command route from an owned parcel into one work desk.
    ParcelRouteAdd {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Slash command prefix to route.
        command_prefix: &'a str,
    },
    /// List command routes for an owned parcel.
    ParcelRouteList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Remove a command route from an owned parcel work desk.
    ParcelRouteRemove {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Slash command prefix to remove.
        command_prefix: &'a str,
    },
    /// List badge definitions for an owned parcel.
    ParcelBadgeList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Create or update a badge definition for an owned parcel.
    ParcelBadgeCreate {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable badge slug.
        slug: &'a str,
        /// Player-facing badge title.
        title: &'a str,
        /// Optional one-line description.
        description: Option<&'a str>,
    },
    /// Award a parcel badge to a user.
    ParcelBadgeAward {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable badge slug.
        slug: &'a str,
        /// Target username or player id.
        target: &'a str,
        /// Optional one-line award note.
        note: Option<&'a str>,
    },
    /// Revoke an active parcel badge award.
    ParcelBadgeRevoke {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable badge slug.
        slug: &'a str,
        /// Target username or player id.
        target: &'a str,
    },
    /// List active badges held by the current player.
    BadgesMine,
    /// List active public badges held by another player.
    BadgesUser {
        /// Target username or player id.
        target: &'a str,
    },
    /// Persist a same-view say message and emit live delivery events.
    Say {
        /// Current room view id.
        current_view: &'a str,
        /// Spoken text.
        text: &'a str,
    },
    /// Persist a direct mail message.
    Mail {
        /// Target mail address or user.
        target: &'a str,
        /// Mail body.
        text: &'a str,
    },
    /// Persist a broadcast message.
    Broadcast {
        /// Broadcast body.
        text: &'a str,
    },
    /// Forward input to an externally hosted service room.
    ServiceRoomInput {
        /// Current service room view id.
        room_view: &'a str,
        /// Raw input to forward.
        raw_input: &'a str,
    },
    /// Render contextual service-room help.
    ServiceRoomHelp {
        /// Current service room view id.
        room_view: &'a str,
    },
    /// Render a structured service-room observation.
    ServiceRoomObservation {
        /// Current service room view id.
        room_view: &'a str,
    },
    /// Render a service-room blocked-exit message.
    ServiceRoomBlockedExit,
    /// Render a service-room unavailable-command message.
    ServiceRoomUnavailable,
    /// Close the current service-room session.
    ServiceRoomQuit {
        /// Quit feedback text supplied by the protocol shell.
        feedback: &'a str,
    },
    /// Mark the active admission agreement as read.
    AdmissionRead,
    /// Accept the active admission agreement.
    AdmissionAccept,
    /// Show account settings.
    Settings {
        /// Display mail address.
        mail_address: &'a str,
    },
    /// Rotate the current user's SMTP/IMAP token.
    SettingsRotateMailToken {
        /// Display mail address.
        mail_address: &'a str,
        /// One-time mail token generated by the caller.
        token: &'a str,
    },
    /// Update one role-card field.
    SettingsUpdateRoleCard {
        /// Display mail address.
        mail_address: &'a str,
        /// Role-card field update.
        update: RoleCardUpdate,
    },
}
