use crate::*;

/// Protocol-neutral request variants currently handled inside `hinemos-app`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AppRequest<'a> {
    /// Build the login memory summary.
    MemoryContext,
    /// Handle a `/memory` subcommand.
    MemoryCommand {
        /// Text after `/memory`.
        rest: &'a str,
    },
    /// Render recent messages for the current room.
    RoomHistory {
        /// Current runtime view id.
        current_view: &'a str,
        /// Current room title.
        title: &'a str,
    },
    /// Render the current player's inventory.
    Inventory {
        /// Current runtime inventory items.
        items: &'a [String],
    },
    /// Render users currently online in this view.
    Who {
        /// Current runtime view id.
        current_view: &'a str,
        /// Usernames currently visible in this view.
        users: &'a [String],
        /// Population counts for the world and online sessions.
        population: WhoPopulation,
    },
    /// Render recent world news.
    News,
    /// Render the current player's MARK balance.
    Balance,
    /// List inbox items.
    InboxList {
        /// Display title.
        title: &'a str,
        /// Inbox filter such as `open`, `unread`, or `all`.
        filter: &'a str,
        /// Optional mail domain for display addresses.
        mail_domain: Option<&'a str>,
    },
    /// Read one inbox item.
    InboxRead {
        /// Inbox item id.
        item_id: i64,
        /// Optional mail domain for display addresses.
        mail_domain: Option<&'a str>,
    },
    /// Claim one inbox item.
    InboxClaim {
        /// Inbox item id.
        item_id: i64,
    },
    /// Acknowledge one inbox item.
    InboxAck {
        /// Inbox item id.
        item_id: i64,
    },
    /// Archive one inbox item.
    InboxArchive {
        /// Inbox item id.
        item_id: i64,
    },
    /// Show the current player's shop operator inbox.
    ShopInbox,
    /// Show pending payment requests for the current player.
    PendingPayRequests,
    /// Transfer MARK directly to another account.
    PayDirect {
        /// Target username or player id.
        target: &'a str,
        /// Positive MARK amount.
        amount: i64,
        /// Payment memo.
        memo: &'a str,
    },
    /// Accept a pending payment request.
    PayAccept {
        /// Payment request id.
        request_id: i64,
    },
    /// List commercial parcels.
    LandList,
    /// Show commercial parcel details.
    LandInfo {
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Show build command help.
    BuildHelp,
    /// Claim a commercial parcel and provision its room mailbox token.
    LandClaim {
        /// Parcel id.
        parcel_id: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Transfer a commercial parcel and rotate its room mailbox token.
    LandTransfer {
        /// Parcel id.
        parcel_id: &'a str,
        /// Target username.
        target: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Rotate a parcel room mailbox token.
    LandRotateToken {
        /// Parcel id.
        parcel_id: &'a str,
        /// One-time room mailbox token generated by the caller.
        token: &'a str,
    },
    /// Apply a structured build sheet to the current parcel room.
    BuildApply {
        /// Current room view id.
        current_view: &'a str,
        /// Structured build sheet.
        sheet: &'a BuildSheet,
    },
    /// Set one build field on the current parcel room.
    BuildSet {
        /// Current room view id.
        current_view: &'a str,
        /// Build field name.
        field: &'a str,
        /// Build field value.
        value: &'a str,
    },
    /// Publish the current parcel room build.
    BuildPublish {
        /// Current room view id.
        current_view: &'a str,
    },
    /// Create a payment request for a shop command.
    ShopRequestPayment {
        /// Operator command id.
        command_id: i64,
        /// Positive MARK amount.
        amount: i64,
        /// Delivery content unlocked after payment.
        delivery: &'a str,
    },
    /// Create a mailing list for an owned shop.
    ShopMailingListCreate {
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable list slug.
        slug: &'a str,
        /// Player-facing list title.
        title: &'a str,
    },
    /// List mailing lists for an owned shop.
    ShopMailingListList {
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Show mailing-list subscribers for an owned shop.
    ShopMailingListSubscribers {
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable list slug.
        slug: &'a str,
    },
    /// Send an owner-authored mailing-list post.
    ShopMailingListSend {
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable list slug.
        slug: &'a str,
        /// Inbox subject.
        subject: &'a str,
        /// Inbox body.
        body: &'a str,
    },
    /// Post a group-chat message to a shop mailing list.
    ShopMailingListChat {
        /// Parcel id or visible shop title.
        target: &'a str,
        /// Stable list slug.
        slug: &'a str,
        /// Message body.
        body: &'a str,
    },
    /// Close a mailing list to new subscriptions.
    ShopMailingListClose {
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable list slug.
        slug: &'a str,
    },
    /// Subscribe the current player to a shop mailing list.
    ShopMailingListSubscribe {
        /// Parcel id or visible shop title.
        target: &'a str,
        /// Stable list slug.
        slug: &'a str,
    },
    /// Unsubscribe the current player from a shop mailing list.
    ShopMailingListUnsubscribe {
        /// Parcel id or visible shop title.
        target: &'a str,
        /// Stable list slug.
        slug: &'a str,
    },
    /// List the current player's shop mailing-list subscriptions.
    ShopMailingListSubscriptions,
    /// Create a shop-local work desk.
    ShopDeskCreate {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Player-facing work-desk title.
        title: &'a str,
    },
    /// List shop-local work desks.
    ShopDeskList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Add a worker to a shop-local work desk.
    ShopStaffAdd {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Worker username.
        username: &'a str,
    },
    /// List workers assigned to a shop-local work desk.
    ShopStaffList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
    },
    /// Remove a worker from a shop-local work desk.
    ShopStaffRemove {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Worker username.
        username: &'a str,
    },
    /// Start an in-shop work shift.
    ShopShiftStart {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
    },
    /// End an in-shop work shift.
    ShopShiftEnd {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
    },
    /// List shop work while inside the shop.
    ShopWorkList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Optional stable work-desk slug.
        slug: Option<&'a str>,
    },
    /// Claim shop work while inside the shop.
    ShopWorkClaim {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Work item id.
        work_id: i64,
    },
    /// Complete claimed shop work while inside the shop.
    ShopWorkDone {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Work item id.
        work_id: i64,
        /// Worker result note.
        result: &'a str,
    },
    /// Add a command route from an owned shop into one work desk.
    ShopRouteAdd {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Slash command prefix to route.
        command_prefix: &'a str,
    },
    /// List command routes for an owned shop.
    ShopRouteList {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Remove a command route from an owned shop work desk.
    ShopRouteRemove {
        /// Current runtime view id.
        current_view: &'a str,
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable work-desk slug.
        slug: &'a str,
        /// Slash command prefix to remove.
        command_prefix: &'a str,
    },
    /// List badge definitions for an owned shop.
    ShopBadgeList {
        /// Parcel id.
        parcel_id: &'a str,
    },
    /// Create or update a badge definition for an owned shop.
    ShopBadgeCreate {
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable badge slug.
        slug: &'a str,
        /// Player-facing badge title.
        title: &'a str,
        /// Optional one-line description.
        description: Option<&'a str>,
    },
    /// Award a shop badge to a user.
    ShopBadgeAward {
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable badge slug.
        slug: &'a str,
        /// Target username or player id.
        target: &'a str,
        /// Optional one-line award note.
        note: Option<&'a str>,
    },
    /// Revoke an active shop badge award.
    ShopBadgeRevoke {
        /// Parcel id.
        parcel_id: &'a str,
        /// Stable badge slug.
        slug: &'a str,
        /// Target username or player id.
        target: &'a str,
    },
    /// List active badges held by the current player.
    BadgesMine,
    /// List active public badges held by another player.
    BadgesUser {
        /// Target username or player id.
        target: &'a str,
    },
    /// Persist a same-view say message and emit live delivery events.
    Say {
        /// Current room view id.
        current_view: &'a str,
        /// Spoken text.
        text: &'a str,
    },
    /// Persist a direct mail message.
    Mail {
        /// Target mail address or user.
        target: &'a str,
        /// Mail body.
        text: &'a str,
    },
    /// Persist a broadcast message.
    Broadcast {
        /// Broadcast body.
        text: &'a str,
    },
    /// Forward input to an externally hosted service room.
    ServiceRoomInput {
        /// Current service room view id.
        room_view: &'a str,
        /// Raw input to forward.
        raw_input: &'a str,
    },
    /// Render contextual service-room help.
    ServiceRoomHelp {
        /// Current service room view id.
        room_view: &'a str,
    },
    /// Render a structured service-room observation.
    ServiceRoomObservation {
        /// Current service room view id.
        room_view: &'a str,
    },
    /// Render a service-room blocked-exit message.
    ServiceRoomBlockedExit,
    /// Render a service-room unavailable-command message.
    ServiceRoomUnavailable,
    /// Close the current service-room session.
    ServiceRoomQuit {
        /// Quit feedback text supplied by the protocol shell.
        feedback: &'a str,
    },
    /// Mark the active admission agreement as read.
    AdmissionRead,
    /// Accept the active admission agreement.
    AdmissionAccept,
    /// Show account settings.
    Settings {
        /// Display mail address.
        mail_address: &'a str,
    },
    /// Rotate the current user's SMTP/IMAP token.
    SettingsRotateMailToken {
        /// Display mail address.
        mail_address: &'a str,
        /// One-time mail token generated by the caller.
        token: &'a str,
    },
    /// Update one role-card field.
    SettingsUpdateRoleCard {
        /// Display mail address.
        mail_address: &'a str,
        /// Role-card field update.
        update: RoleCardUpdate,
    },
}
