use super::handler_helpers::*;
use super::*;

impl ConnectionHandler {
    pub(super) async fn handle_settings_command(
        &self,
        channel: ChannelId,
        session: &mut Session,
        action: &SettingsAction,
        identity: &AuthIdentity,
    ) -> Result<()> {
        match action {
            SettingsAction::Show => {
                let settings = self
                    .shared
                    .storage
                    .account_settings(&identity.user, &identity.player_id)
                    .await?;
                let mail_address =
                    format_mail_user(&identity.user, self.shared.mail_domain.as_deref());
                let key = settings.key_fingerprint.as_deref().unwrap_or("not set");
                let mut next_steps = Vec::new();
                if !settings.has_mail_token {
                    next_steps.push("Generate your SMTP/IMAP token with /settings mail-token.");
                }
                let next_steps = if next_steps.is_empty() {
                    "Next steps: account settings are complete.\r\n".to_owned()
                } else {
                    format!("Next steps:\r\n- {}\r\n", next_steps.join("\r\n- "))
                };
                let agent_protocol = format!(
                    "Agent realtime mail:\r\n- Login: IMAP/SMTP username `{}`; token is generated by `/settings mail-token`.\r\n- Setup: use ed25519 SSH login for account access.\r\n- Listen: keep an IMAP IDLE connection open; when EXISTS arrives, FETCH the new message, handle it, then STORE +FLAGS (\\Seen). This is the supported no-prompt path for autonomous agents.\r\n",
                    identity.user
                );
                session.data(
                    channel,
                    format!(
                        "Settings\r\nUser: {}\r\nPlayer: {}\r\nDisplay name: {}\r\nOnline days: {}\r\nSSH key: {}\r\nMail address: {}\r\nMail token: {}\r\n{}{}Use /settings mail-token to generate or rotate your SMTP/IMAP token.\r\n",
                        identity.user,
                        settings.player_id,
                        settings.display_name,
                        settings.online_days,
                        key,
                        mail_address,
                        enabled_label(settings.has_mail_token),
                        next_steps,
                        agent_protocol,
                    )
                    .into_bytes(),
                )?;
            }
            SettingsAction::MailToken => {
                let token = generate_mail_auth_token();
                self.shared
                    .storage
                    .set_mail_auth_token(&identity.user, &identity.player_id, &token)
                    .await?;
                let address = format_mail_user(&identity.user, self.shared.mail_domain.as_deref());
                session.data(
                    channel,
                    format!(
                        "Generated a new SMTP/IMAP mail auth token.\r\nUsername: {}\r\nAddress: {}\r\nToken: {}\r\nThis token is shown once; run /settings mail-token again to rotate it.\r\nAgent setup: configure SMTP and IMAP with this username/token. For realtime autonomous handling, keep an IMAP IDLE listener open and process EXISTS notifications without waiting for a world prompt.\r\n",
                        identity.user, address, token
                    )
                    .into_bytes(),
                )?;
            }
        }
        Ok(())
    }

    pub(super) async fn handle_enter_command(
        &self,
        channel: ChannelId,
        session: &mut Session,
        target: &str,
        identity: &AuthIdentity,
    ) -> Result<()> {
        let mut player = self
            .shared
            .runtime
            .player_state(&identity.player_id)
            .await?;
        let parcels = self.shared.storage.list_commercial_parcels().await?;
        let visible = visible_street_parcels(&player.current_view, &parcels);
        if let Some((view_id, label)) = self
            .resolve_visible_shopfront_enter(&player.current_view, target, &identity.player_id)
            .await?
        {
            player.current_view = view_id;
            self.shared.runtime.set_player_state(player.clone()).await?;
            PlayerStateStore::save_player_state(&self.shared.storage, &player).await?;
            self.shared
                .presence
                .lock()
                .await
                .update_view(self.connection_id, player.current_view.clone());

            session.data(channel, format!("You enter {label}.\r\n").into_bytes())?;
            let observation = self.observe_current_json(&identity.player_id).await?;
            self.send_text_observation(channel, session, observation)
                .await?;
            return Ok(());
        }

        let parcel = resolve_enter_target(&visible, target)?;

        player.current_view = parcel.view_id.clone();
        self.shared.runtime.set_player_state(player.clone()).await?;
        PlayerStateStore::save_player_state(&self.shared.storage, &player).await?;
        self.shared
            .presence
            .lock()
            .await
            .update_view(self.connection_id, player.current_view.clone());

        session.data(
            channel,
            format!("You enter {}.\r\n", parcel.parcel_id).into_bytes(),
        )?;
        let observation = self.observe_current_json(&identity.player_id).await?;
        self.send_text_observation(channel, session, observation)
            .await?;
        Ok(())
    }

    pub(super) async fn resolve_visible_shopfront_enter(
        &self,
        current_view: &str,
        target: &str,
        player_id: &str,
    ) -> Result<Option<(String, String)>> {
        let normalized = normalize_enter_target(target);
        if normalized.is_empty() {
            return Ok(None);
        }
        let observation = self.shared.runtime.observe_json(player_id).await?;
        let rooms = self
            .shared
            .storage
            .service_rooms_by_front_view(current_view)
            .await?;
        for room in rooms {
            let Some(front_entity_id) = room.front_entity_id.as_deref() else {
                continue;
            };
            if !observation
                .entities
                .iter()
                .any(|entity| entity.id == front_entity_id)
            {
                continue;
            }
            if service_room_enter_matches(&room, &normalized) {
                return Ok(Some((
                    room.view_id,
                    room.label.unwrap_or_else(|| front_entity_id.to_owned()),
                )));
            }
        }
        Ok(None)
    }

    pub(super) async fn handle_operator_input(
        &self,
        channel: ChannelId,
        session: &mut Session,
        line: &str,
        identity: &AuthIdentity,
        prompt: bool,
    ) -> Result<bool> {
        let player = self
            .shared
            .runtime
            .player_state(&identity.player_id)
            .await?;
        let Some(parcel) = self
            .shared
            .storage
            .commercial_parcel_by_view(&player.current_view)
            .await?
        else {
            return Ok(false);
        };
        if parcel.status != "built" {
            return Ok(false);
        }
        let Some(owner_player_id) = parcel.owner_player_id.as_deref() else {
            return Ok(false);
        };
        if owner_player_id == identity.player_id {
            if is_custom_command_input(&parcel, line) {
                session.data(
                    channel,
                    format!(
                        "You own this shop. Visitors use {} here; their requests arrive in your inbox and /shop inbox.\r\n",
                        line.split_whitespace().next().unwrap_or("this command")
                    )
                    .into_bytes(),
                )?;
                if prompt {
                    send_prompt(session, channel)?;
                }
                return Ok(true);
            }
            return Ok(false);
        }

        let recipients = self
            .shared
            .presence
            .lock()
            .await
            .direct_recipients(self.connection_id, owner_player_id);
        let delivered = !recipients.is_empty();
        let command = self
            .shared
            .storage
            .save_operator_command(
                &parcel,
                &identity.user,
                &identity.player_id,
                line,
                delivered,
            )
            .await?;
        let inbox_item = self
            .shared
            .storage
            .inbox_item_by_source(owner_player_id, "operator_command", command.id)
            .await?;
        if delivered {
            deliver_live_inbox_notice(recipients, &inbox_item, self.shared.mail_domain.as_deref())
                .await;
        }
        session.data(
            channel,
            format!(
                "Shop request #{} sent to owner {} for parcel {}.\r\nStatus: {}.\r\n{}",
                command.id,
                command.owner_user,
                command.parcel_id,
                if delivered { "delivered" } else { "queued" },
                custom_command_preview(&parcel, line)
                    .map(|preview| format!("Preview: {preview}\r\n"))
                    .unwrap_or_default()
            )
            .into_bytes(),
        )?;
        if prompt {
            send_prompt(session, channel)?;
        }
        Ok(true)
    }

    pub(super) async fn handle_pay_command(
        &self,
        channel: ChannelId,
        session: &mut Session,
        action: &PayAction,
        identity: &AuthIdentity,
    ) -> Result<()> {
        match action {
            PayAction::Direct {
                target,
                amount,
                memo,
            } => {
                let transfer = self
                    .shared
                    .storage
                    .transfer_mark(&identity.user, &identity.player_id, target, *amount, memo)
                    .await?;
                session.data(
                    channel,
                    format!(
                        "Paid {} {} to {}. Ledger #{}. Balance: {} {}.\r\n",
                        transfer.amount,
                        transfer.asset,
                        transfer.target_user,
                        transfer.ledger_id,
                        transfer.sender_balance,
                        transfer.asset
                    )
                    .into_bytes(),
                )?;
                let recipients = self
                    .shared
                    .presence
                    .lock()
                    .await
                    .direct_recipients(self.connection_id, target);
                if !recipients.is_empty() {
                    let memo_text = if transfer.memo.is_empty() {
                        String::new()
                    } else {
                        format!(" memo={}", transfer.memo)
                    };
                    deliver_live_message(
                        recipients,
                        &format!(
                            "[payment from {}] {} {}{}",
                            identity.user, transfer.amount, transfer.asset, memo_text
                        ),
                    )
                    .await;
                }
            }
            PayAction::Requests => {
                let requests = self
                    .shared
                    .storage
                    .pending_payment_requests(&identity.player_id, 20)
                    .await?;
                send_payment_request_list(session, channel, &requests)?;
            }
            PayAction::Accept { request_id } => {
                let (request, sender_balance) = self
                    .shared
                    .storage
                    .accept_payment_request(&identity.user, &identity.player_id, *request_id)
                    .await?;
                session.data(
                    channel,
                    render_paid_request(&request, sender_balance).into_bytes(),
                )?;
                let recipients = self
                    .shared
                    .presence
                    .lock()
                    .await
                    .direct_recipients(self.connection_id, &request.payee_player_id);
                if !recipients.is_empty() {
                    deliver_live_message(
                        recipients,
                        &format!(
                            "[payment request #{} paid by {}] {} {}",
                            request.id, identity.user, request.amount, request.asset
                        ),
                    )
                    .await;
                }
            }
        }
        Ok(())
    }

    pub(super) async fn handle_inbox_command(
        &self,
        channel: ChannelId,
        session: &mut Session,
        action: &InboxAction,
        identity: &AuthIdentity,
    ) -> Result<()> {
        match action {
            InboxAction::List { filter } => {
                let items = self
                    .shared
                    .storage
                    .list_inbox_items(&identity.user, &identity.player_id, Some(filter), 20)
                    .await?;
                session.data(
                    channel,
                    render_inbox_items("Inbox", &items, self.shared.mail_domain.as_deref())
                        .replace('\n', "\r\n")
                        .into_bytes(),
                )?;
            }
            InboxAction::Read { item_id } => {
                let item = self
                    .shared
                    .storage
                    .read_inbox_item(&identity.user, &identity.player_id, *item_id)
                    .await?;
                session.data(
                    channel,
                    render_inbox_item(&item, self.shared.mail_domain.as_deref())
                        .replace('\n', "\r\n")
                        .into_bytes(),
                )?;
            }
            InboxAction::Claim { item_id } => {
                let item = self
                    .shared
                    .storage
                    .claim_inbox_item(&identity.user, &identity.player_id, *item_id)
                    .await?;
                session.data(
                    channel,
                    format!(
                        "Claimed inbox #{} kind={} subject={}. Lease until {}.\r\n",
                        item.id,
                        item.kind,
                        item.subject,
                        item.lease_until.as_deref().unwrap_or("unknown")
                    )
                    .into_bytes(),
                )?;
            }
            InboxAction::Ack { item_id } => {
                let item = self
                    .shared
                    .storage
                    .finish_inbox_item(&identity.user, &identity.player_id, *item_id, "acked")
                    .await?;
                session.data(
                    channel,
                    format!("Acked inbox #{} kind={}.\r\n", item.id, item.kind).into_bytes(),
                )?;
            }
            InboxAction::Archive { item_id } => {
                let item = self
                    .shared
                    .storage
                    .finish_inbox_item(&identity.user, &identity.player_id, *item_id, "archived")
                    .await?;
                session.data(
                    channel,
                    format!("Archived inbox #{} kind={}.\r\n", item.id, item.kind).into_bytes(),
                )?;
            }
        }
        Ok(())
    }

    pub(super) async fn handle_land_command(
        &self,
        channel: ChannelId,
        session: &mut Session,
        action: &LandAction,
        identity: &AuthIdentity,
    ) -> Result<()> {
        match action {
            LandAction::List => {
                let parcels = self.shared.storage.list_commercial_parcels().await?;
                session.data(
                    channel,
                    render_parcel_list(&parcels)
                        .replace('\n', "\r\n")
                        .into_bytes(),
                )?;
            }
            LandAction::Info { parcel_id } => {
                let parcel = self.shared.storage.commercial_parcel(parcel_id).await?;
                session.data(
                    channel,
                    render_parcel_detail(&parcel)
                        .replace('\n', "\r\n")
                        .into_bytes(),
                )?;
            }
            LandAction::Claim { parcel_id } => {
                let parcel = self
                    .shared
                    .storage
                    .claim_commercial_parcel(parcel_id, &identity.user, &identity.player_id)
                    .await?;
                let token = generate_mail_auth_token();
                let mail = self
                    .shared
                    .storage
                    .set_room_mail_auth_token(parcel_id, &identity.player_id, &token)
                    .await?;
                session.data(
                    channel,
                    format!(
                        "Claimed parcel {}. Room mail account: {}. Token: {}\r\nUse this token from the room owner process with SMTP/IMAP. You can rotate it later with /land token {}.\r\nBuild here with /build {{\"title\":\"...\",\"description\":\"...\",\"style\":\"...\",\"prompt\":\"...\"}}, then /build publish. From the street, enter with /enter {}. Custom commands are auto-filled if omitted.\r\n",
                        parcel.parcel_id, mail.username, token, parcel.parcel_id, parcel.parcel_id
                    )
                    .into_bytes(),
                )?;
            }
            LandAction::Transfer { parcel_id, target } => {
                let parcel = self
                    .shared
                    .storage
                    .transfer_commercial_parcel(parcel_id, &identity.player_id, target)
                    .await?;
                let token = generate_mail_auth_token();
                let mail = self
                    .shared
                    .storage
                    .set_room_mail_auth_token(
                        parcel_id,
                        parcel.owner_player_id.as_deref().unwrap_or_default(),
                        &token,
                    )
                    .await?;
                session.data(
                    channel,
                    format!(
                        "Transferred parcel {} to {}.\r\nNew room mail account: {}. Token: {}\r\nGive this token to the new room owner process; the old room token has been rotated.\r\n",
                        parcel.parcel_id,
                        parcel.owner_user.as_deref().unwrap_or("unknown"),
                        mail.username,
                        token
                    )
                    .into_bytes(),
                )?;
            }
            LandAction::Token { parcel_id } => {
                let token = generate_mail_auth_token();
                let mail = self
                    .shared
                    .storage
                    .set_room_mail_auth_token(parcel_id, &identity.player_id, &token)
                    .await?;
                session.data(
                    channel,
                    format!(
                        "Room mail account for {}: {}\r\nToken: {}\r\nUse SMTP/IMAP with this username/token. This token is shown once; run /land token {} again to rotate it.\r\n",
                        parcel_id, mail.username, token, parcel_id
                    )
                    .into_bytes(),
                )?;
            }
        }
        Ok(())
    }

    pub(super) async fn handle_build_command(
        &self,
        channel: ChannelId,
        session: &mut Session,
        action: &BuildAction,
        identity: &AuthIdentity,
    ) -> Result<()> {
        let player = self
            .shared
            .runtime
            .player_state(&identity.player_id)
            .await?;
        match action {
            BuildAction::Help => {
                session.data(channel, build_help().as_bytes().to_vec())?;
            }
            BuildAction::Apply { sheet } => {
                let mut updated = Vec::new();
                for (field, value) in [
                    ("title", sheet.title.as_deref()),
                    ("description", sheet.description.as_deref()),
                    ("style", sheet.style.as_deref()),
                    ("prompt", sheet.prompt.as_deref()),
                    ("commands", sheet.commands.as_deref()),
                ] {
                    let Some(value) = non_empty(value) else {
                        continue;
                    };
                    self.shared
                        .storage
                        .update_parcel_build_field(
                            &player.current_view,
                            &identity.player_id,
                            field,
                            value,
                        )
                        .await?;
                    updated.push(field);
                }
                if non_empty(sheet.commands.as_deref()).is_none() {
                    self.shared
                        .storage
                        .update_parcel_build_field(
                            &player.current_view,
                            &identity.player_id,
                            "commands",
                            default_build_commands(),
                        )
                        .await?;
                    updated.push("commands");
                }
                if updated.is_empty() {
                    anyhow::bail!("build JSON did not include editable fields");
                }
                session.data(
                    channel,
                    format!(
                        "Updated build sheet for current parcel: {}.\r\n",
                        updated.join(", ")
                    )
                    .into_bytes(),
                )?;
            }
            BuildAction::Set { field, value } => {
                let parcel = self
                    .shared
                    .storage
                    .update_parcel_build_field(
                        &player.current_view,
                        &identity.player_id,
                        field,
                        value,
                    )
                    .await?;
                session.data(
                    channel,
                    format!("Updated {} for parcel {}.\r\n", field, parcel.parcel_id).into_bytes(),
                )?;
            }
            BuildAction::Publish => {
                let parcel = self
                    .shared
                    .storage
                    .publish_parcel_build(&player.current_view, &identity.player_id)
                    .await?;
                session.data(
                    channel,
                    format!("Published parcel {} as a built shop.\r\n", parcel.parcel_id)
                        .into_bytes(),
                )?;
            }
        }
        Ok(())
    }

    pub(super) async fn handle_shop_command(
        &self,
        channel: ChannelId,
        session: &mut Session,
        action: &ShopAction,
        identity: &AuthIdentity,
    ) -> Result<()> {
        match action {
            ShopAction::Inbox => {
                let commands = self
                    .shared
                    .storage
                    .recent_operator_commands(&identity.player_id, 20)
                    .await?;
                send_operator_command_list(session, channel, &commands)?;
            }
            ShopAction::RequestPayment {
                command_id,
                amount,
                delivery,
            } => {
                let request = self
                    .shared
                    .storage
                    .create_payment_request(*command_id, &identity.player_id, *amount, delivery)
                    .await?;
                let inbox_item = self
                    .shared
                    .storage
                    .inbox_item_by_source(&request.payer_player_id, "payment_request", request.id)
                    .await?;
                session.data(
                    channel,
                    format!(
                        "Created payment request #{} for {}: {} {}. Delivery is locked until payment.\r\n",
                        request.id, request.payer_user, request.amount, request.asset
                    )
                    .into_bytes(),
                )?;
                let recipients = self
                    .shared
                    .presence
                    .lock()
                    .await
                    .direct_recipients(self.connection_id, &request.payer_player_id);
                if !recipients.is_empty() {
                    deliver_live_inbox_notice(
                        recipients,
                        &inbox_item,
                        self.shared.mail_domain.as_deref(),
                    )
                    .await;
                }
            }
        }
        Ok(())
    }
}
